import{describe,it,expect,beforeEach,afterEach,vi}from"vitest";
import{loadState,saveState,exportState,importState,createLocalRepository}from"./storage";

describe("storage migration",()=>{
 const store=new Map();
 beforeEach(()=>{store.clear();vi.stubGlobal("localStorage",{getItem:key=>store.get(key)||null,setItem:(key,value)=>store.set(key,value)});});
 afterEach(()=>vi.unstubAllGlobals());
 it("returns a clean v6 state when storage is empty",()=>{const state=loadState();expect(state.schemaVersion).toBe(6);expect(state.activeGoalId).toBe("");});
 it("migrates a legacy single-goal state and scopes actions to that goal",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:5,goals:[{id:"g1",title:"Learn"}],actions:[{id:"a1",title:"Study"}]}));const state=loadState();expect(state.schemaVersion).toBe(6);expect(state.activeGoalId).toBe("g1");expect(state.goals[0].status).toBe("active");expect(state.goals[0].planVersion).toBe(1);expect(state.actions[0].goalId).toBe("g1");expect(state.actions[0].status).toBe("open");});
 it("preserves an explicit active goal and its version",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:5,activeGoalId:"g2",goals:[{id:"g1",status:"archived"},{id:"g2",status:"active",planVersion:3}],actions:[]}));const state=loadState();expect(state.activeGoalId).toBe("g2");expect(state.goals[0].status).toBe("archived");expect(state.goals[1].planVersion).toBe(3);});
 it("recovers when the persisted active goal is archived or missing",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:5,activeGoalId:"gone",goals:[{id:"g1",status:"archived"},{id:"g2",status:"active"}],actions:[]}));expect(loadState().activeGoalId).toBe("g2");store.set("aspirra-state-v6",JSON.stringify({schemaVersion:5,activeGoalId:"g1",goals:[{id:"g1",status:"archived"},{id:"g2",status:"active"}],actions:[]}));expect(loadState().activeGoalId).toBe("g2");});
 it("falls back to a clean state for malformed persisted JSON",()=>{store.set("aspirra-state-v6","{not-json");const state=loadState();expect(state.schemaVersion).toBe(6);expect(state.goals).toEqual([]);expect(state.activeGoalId).toBe("");});
 it("recovers from a valid backup when the primary snapshot is corrupted",()=>{store.set("aspirra-state-v6","{not-json");store.set("aspirra-state-v6-backup",JSON.stringify({schemaVersion:6,activeGoalId:"safe",goals:[{id:"safe",title:"Keep going",status:"active"}],actions:[]}));const state=loadState();expect(state.activeGoalId).toBe("safe");expect(state.goals[0].title).toBe("Keep going");expect(JSON.parse(store.get("aspirra-state-v6")).activeGoalId).toBe("safe");});
 it("normalizes malformed collection fields",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:5,goals:{id:"g1"},actions:"bad",completedActionIds:null,memory:"bad"}));const state=loadState();expect(state.schemaVersion).toBe(6);expect(state.goals).toEqual([]);expect(state.actions).toEqual([]);expect(state.completedActionIds).toEqual([]);expect(state.reflections).toEqual([]);expect(state.memory.preferences).toEqual([]);});
 it("rejects a persisted primitive root",()=>{store.set("aspirra-state-v6",JSON.stringify("bad"));const state=loadState();expect(state.schemaVersion).toBe(6);expect(state.goals).toEqual([]);});
 it("preserves completed and archived goal status",()=>{store.set("aspirra-state-v6",JSON.stringify({goals:[{id:"g1",status:"completed"},{id:"g2",status:"archived"}],actions:[]}));const state=loadState();expect(state.goals.map(g=>g.status)).toEqual(["completed","archived"]);});
 it("exports and imports a portable state snapshot",()=>{const backup=exportState({activeGoalId:"g1",goals:[{id:"g1",title:"Keep going",status:"active"}],actions:[]});const restored=importState(backup);expect(restored.schemaVersion).toBe(6);expect(restored.activeGoalId).toBe("g1");expect(restored.goals[0].title).toBe("Keep going")});
 it("exposes a local repository contract",()=>{const repository=createLocalRepository();const state=repository.load();expect(state.schemaVersion).toBe(6);expect(typeof repository.save).toBe("function");expect(typeof repository.export).toBe("function");expect(typeof repository.import).toBe("function")});
 it("persists state with the current schema version",()=>{saveState({activeGoalId:"g1",goals:[],actions:[]});const saved=JSON.parse(store.get("aspirra-state-v6"));expect(saved.schemaVersion).toBe(6);expect(saved.activeGoalId).toBe("g1");});
 it("still saves the new snapshot when backup rotation fails",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:6,activeGoalId:"old"}));vi.stubGlobal("localStorage",{getItem:key=>store.get(key)||null,setItem:(key,value)=>{if(key==="aspirra-state-v6-backup")throw new Error("quota");store.set(key,value)}});expect(saveState({activeGoalId:"new",goals:[],actions:[]})).toBe(true);expect(JSON.parse(store.get("aspirra-state-v6")).activeGoalId).toBe("new")});
 it("keeps the previous snapshot when serialization fails",()=>{store.set("aspirra-state-v6",JSON.stringify({schemaVersion:6,activeGoalId:"safe"}));const circular={};circular.self=circular;expect(saveState({activeGoalId:"unsafe",circular})).toBe(false);expect(JSON.parse(store.get("aspirra-state-v6")).activeGoalId).toBe("safe");});
});