export const SYNC_DECISIONS=Object.freeze({NOOP:"noop",PUSH:"push",PULL:"pull",CONFLICT:"conflict"});
export function createDeviceId(random=()=>Math.random().toString(36).slice(2)){const key="aspirra-device-id";try{const existing=localStorage.getItem(key);if(existing)return existing;const id="device-"+Date.now().toString(36)+"-"+random();localStorage.setItem(key,id);return id}catch{return"device-"+Date.now().toString(36)+"-"+random()}}
export function compareRevisions(local,remote){const l=Number.isFinite(local?.revision)?local.revision:0;const r=Number.isFinite(remote?.revision)?remote.revision:0;if(r===l)return{decision:SYNC_DECISIONS.NOOP,localRevision:l,remoteRevision:r};if(r>l)return{decision:SYNC_DECISIONS.PULL,localRevision:l,remoteRevision:r};return{decision:SYNC_DECISIONS.PUSH,localRevision:l,remoteRevision:r}}
export function buildSyncEnvelope(state,deviceId){return{formatVersion:1,schemaVersion:state.schemaVersion||6,revision:Number.isFinite(state.sync?.revision)?state.sync.revision:0,deviceId:deviceId||state.sync?.deviceId||"",updatedAt:new Date().toISOString(),account:{mode:state.account?.mode||"local",userId:state.account?.userId||""},state}}
export function validateSyncEnvelope(envelope){if(!envelope||typeof envelope!=="object"||!envelope.state||typeof envelope.state!=="object")return{valid:false,reason:"invalid-envelope"};if(envelope.formatVersion!==1)return{valid:false,reason:"unsupported-format"};if(!Number.isFinite(envelope.revision)||envelope.revision<0)return{valid:false,reason:"invalid-revision"};if(typeof envelope.deviceId!=="string")return{valid:false,reason:"invalid-device"};return{valid:true}}
export function buildConflictReport(local,remote){return{type:"revision-conflict",local:{revision:local?.revision||0,deviceId:local?.deviceId||""},remote:{revision:remote?.revision||0,deviceId:remote?.deviceId||""},requiresUserReview:true}}
export function nextSyncRevision(state){const current=Number.isFinite(state?.sync?.revision)?state.sync.revision:0;return current+1}
export function prepareSyncState(state){const revision=nextSyncRevision(state);return{...state,sync:{...(state.sync||{}),status:"syncing",revision}}}
export function applyRemoteRevision(state,remoteRevision){const revision=Number.isFinite(remoteRevision)?remoteRevision:state.sync?.revision||0;return{...state,sync:{...(state.sync||{}),status:"synced",revision,lastSyncedAt:new Date().toISOString()}}}
