import{useMemo,useState}from"react";import{ArrowRight,Bot,CheckCircle2,Compass,Plus,Sparkles,Target,TrendingUp,X}from"lucide-react";import{loadState,saveState}from"./lib/storage";import{createStarterPlan}from"./lib/planner";
const initial=loadState();
function App(){const[state,setState]=useState(initial),[view,setView]=useState("home"),[goal,setGoal]=useState(""),[showGoal,setShowGoal]=useState(false);
const completed=state.completedActionIds.length,total=state.actions.length,progress=total?Math.round(completed/total*100):0,currentGoal=state.goals[state.goals.length-1];
function persist(next){setState(next);saveState(next)}
function createGoal(e){e.preventDefault();if(!goal.trim())return;const plan=createStarterPlan(goal),next={...state,goals:[...state.goals,{id:crypto.randomUUID(),title:plan.title,createdAt:new Date().toISOString()}],actions:[...state.actions,...plan.actions]};persist(next);setGoal("");setShowGoal(false);setView("home")}
function toggleAction(id){const exists=state.completedActionIds.includes(id),next={...state,completedActionIds:exists?state.completedActionIds.filter(x=>x!==id):[...state.completedActionIds,id]};persist(next)}
const todayActions=useMemo(()=>state.actions.filter(a=>!state.completedActionIds.includes(a.id)).slice(0,3),[state.actions,state.completedActionIds]);
return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">A</span><span>Aspirra</span></div><button className="icon-button" aria-label="New goal" onClick={()=>setShowGoal(true)}><Plus size={21}/></button></header>
<main className="content">{view==="home"&&<><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> PERSONAL PROGRESS SYSTEM</span><h1>Turn what you want into <span>what you do.</span></h1><p>Aspirra helps you turn goals into practical plans, daily actions, and measurable progress.</p></div><button className="primary-button" onClick={()=>setShowGoal(true)}>Start a goal <ArrowRight size={18}/></button></section>
<section className="progress-card"><div className="card-heading"><div><span className="label">YOUR PROGRESS</span><h2>{progress}% moving forward</h2></div><div className="progress-ring"><span>{progress}%</span></div></div><div className="progress-track"><span style={{width:progress+"%"}}/></div><p>{total?completed+" of "+total+" planned actions completed.":"Create your first goal to start building your progress history."}</p></section>
<section className="section"><div className="section-title"><span className="label">TODAY</span><h2>What should I do today?</h2></div>{todayActions.length?todayActions.map(action=><button className="action-card" key={action.id} onClick={()=>toggleAction(action.id)}><span className="check"><CheckCircle2 size={21}/></span><span><strong>{action.title}</strong><small>{action.detail}</small></span></button>):<div className="empty-card"><Target size={26}/><strong>{currentGoal?"You’re caught up.":"Start with one meaningful goal."}</strong><p>{currentGoal?"Revisit your plan when your priorities change.":"Tell Aspirra what you want to achieve and we'll turn it into a practical starting plan."}</p></div>}</section>
<section className="feature-grid"><button onClick={()=>setView("guide")}><span className="feature-icon"><Bot size={20}/></span><strong>AI Guide</strong><small>Think through your next move.</small></button><button onClick={()=>setView("progress")}><span className="feature-icon"><TrendingUp size={20}/></span><strong>Progress</strong><small>See what's moving and what's stuck.</small></button><button onClick={()=>setView("goals")}><span className="feature-icon"><Compass size={20}/></span><strong>Goals</strong><small>Keep your bigger direction visible.</small></button></section></>}
{view==="goals"&&<Page title="Goals" subtitle="The outcomes you are working toward."><div className="empty-card">{state.goals.length?state.goals.map(g=><span className="goal-row" key={g.id}>{g.title}</span>):<><Target size={28}/><strong>No goals yet</strong><p>Your first goal becomes the anchor for your plan and daily actions.</p></>}<button className="primary-button" onClick={()=>setShowGoal(true)}>Create goal</button></div></Page>}
{view==="progress"&&<Page title="Progress" subtitle="A simple view of movement, not just activity."><div className="progress-card"><div className="big-number">{progress}%</div><p>{completed} completed actions out of {total} planned actions.</p></div></Page>}
{view==="guide"&&<Page title="AI Guide" subtitle="The intelligence layer will help you reason about goals, blockers, and next actions."><div className="guide-card"><Bot size={30}/><h2>Your guide is being built.</h2><p>The foundation is live. The next AI milestone will connect Aspirra to a model provider, memory, tools, and a structured planning engine.</p><button className="primary-button" onClick={()=>setShowGoal(true)}>Give it a goal</button></div></Page>}</main>
<nav className="bottom-nav">{[["home","Home"],["goals","Goals"],["progress","Progress"],["guide","AI Guide"]].map(([id,label])=><button className={view===id?"active":""} key={id} onClick={()=>setView(id)}>{id==="home"?<Compass/>:id==="goals"?<Target/>:id==="progress"?<TrendingUp/>:<Bot/>}<span>{label}</span></button>)}</nav>
{showGoal&&<div className="modal-backdrop" onClick={()=>setShowGoal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowGoal(false)}><X/></button><span className="eyebrow"><Target size={14}/> NEW GOAL</span><h2>What are you trying to achieve?</h2><p>Start with the outcome. Aspirra will turn it into practical first actions.</p><form onSubmit={createGoal}><textarea autoFocus value={goal} onChange={e=>setGoal(e.target.value)} placeholder="e.g. I want to find a better-paying job within six months."/><button className="primary-button" type="submit">Build my first plan <ArrowRight size={18}/></button></form></div></div>}</div>}
function Page({title,subtitle,children}){return <section className="page"><span className="label">ASPIRRA</span><h1>{title}</h1><p className="page-subtitle">{subtitle}</p>{children}</section>}export default App;