import{useMemo,useState}from"react";import{ArrowRight,Bot,CheckCircle2,Compass,Plus,Sparkles,Target,TrendingUp,X,Brain,AlertCircle}from"lucide-react";import{loadState,saveState}from"./lib/storage";import{createStarterPlan,createAIPlan}from"./lib/planner";import{requestAIPlan,requestAIGuide,requestAIReplan,hasRemoteAI}from"./lib/api";import{analyzeBlocker,buildIntelligence}from"./lib/intelligence";import{calculateProgress,buildReview,addEvidence}from"./lib/progress";import{createGoalRecord,attachActions,createPlanRevision}from"./lib/domain";import{addMemory,removeMemory,buildContext}from"./lib/memory";import{buildToday,deferAction,completeAction}from"./lib/daily";
const initial=loadState();
function App(){const[state,setState]=useState(initial),[view,setView]=useState("home"),[goal,setGoal]=useState(""),[showGoal,setShowGoal]=useState(false),[blocker,setBlocker]=useState(""),[blockerResult,setBlockerResult]=useState(null),[guideInput,setGuideInput]=useState(""),[guideReply,setGuideReply]=useState(""),[guideBusy,setGuideBusy]=useState(false);
const currentGoal=state.goals[state.goals.length-1];const currentStats=currentGoal?calculateProgress(state,currentGoal.id):{percent:0,total:state.actions.length,completed:state.completedActionIds.length};const completed=currentStats.completed,total=currentStats.total,progress=currentStats.percent;
function persist(next){setState(next);saveState(next)}
async function createGoal(e){e.preventDefault();if(!goal.trim())return;let plan=createStarterPlan(goal);if(hasRemoteAI()){try{const ai=await requestAIPlan(goal,{memory:state.memory,previousGoals:state.goals.slice(-5)});plan=createAIPlan(goal,ai)}catch(error){console.warn("AI planning unavailable; using local planner.",error)}}const goalRecord=createGoalRecord(plan);const scopedActions=attachActions(plan.actions,goalRecord.id);const next={...state,goals:[...state.goals,goalRecord],actions:[...state.actions,...scopedActions]};persist(next);setGoal("");setShowGoal(false);setView("home")}
function toggleAction(id){const exists=state.completedActionIds.includes(id);persist(exists?{...state,completedActionIds:state.completedActionIds.filter(x=>x!==id)}:completeAction(state,id))}
function addContextItem(type){const value=window.prompt(type==="preferences"?"What should Aspirra know about how you like to work?":type==="constraints"?"What constraint should Aspirra account for?":"What important context should Aspirra remember?");if(value?.trim())persist(addMemory(state,type,value))} 
async function askGuide(e){e.preventDefault();const message=guideInput.trim();if(!message)return;setGuideBusy(true);try{if(hasRemoteAI()){const result=await requestAIGuide(message,{...buildContext(state),today:buildToday(state),progress:currentStats,evidence:state.evidence?.slice(-5),blockers:state.blockers?.slice(-5)});setGuideReply(result.answer||result.message||"I could not produce a guide response.")}else{const insight=currentGoal?buildIntelligence(currentGoal.title):null;setGuideReply(insight?message.toLowerCase().includes("today")?"Start with: "+(todayActions[0]?.title||"define your smallest next action")+". Then create evidence of completion.":"Your current focus is "+insight.domain+". The next useful question is: "+insight.nextQuestion:"Create a goal first so I can guide the next step.")}}catch(error){setGuideReply("I couldn't reach the AI guide, so use the next unfinished action as your immediate step.");console.warn(error)}finally{setGuideBusy(false)}}
function deleteContextItem(type,id){persist(removeMemory(state,type,id))}
function deferTodayAction(id){const reason=window.prompt("Why are you deferring this action?","Not enough time today");if(reason?.trim())persist(deferAction(state,id,reason))}
function recordEvidence(e){e.preventDefault();const text=e.currentTarget.elements.evidence.value.trim();if(!text||!currentGoal)return;persist(addEvidence(state,currentGoal.id,text));e.currentTarget.reset()}
async function revisePlan(){if(!currentGoal)return;const reason="Progress review requested a plan adjustment.";let plan=createStarterPlan(currentGoal.title);let source="local-replan";if(hasRemoteAI()){try{const ai=await requestAIReplan(currentGoal.title,{goal:currentGoal,openActions:state.actions.filter(a=>a.goalId===currentGoal.id&&a.status!=="archived"&&!state.completedActionIds.includes(a.id)),completedActionIds:state.completedActionIds.filter(id=>state.actions.some(a=>a.id===id&&a.goalId===currentGoal.id)),evidence:(state.evidence||[]).filter(e=>e.goalId===currentGoal.id).slice(-10),blockers:(state.blockers||[]).slice(-10),deferredActions:(state.deferredActions||[]).filter(d=>state.actions.some(a=>a.id===d.actionId&&a.goalId===currentGoal.id)).slice(-10),memory:buildContext(state)});plan=createAIPlan(currentGoal.title,ai);source="ai-replan"}catch(error){console.warn("AI replanning unavailable; using local replanner.",error)}}const revision=createPlanRevision(currentGoal,reason);const nextActions=attachActions(plan.actions,currentGoal.id).map(a=>({...a,source}));const archivedIds=new Set(state.actions.filter(a=>a.goalId===currentGoal.id&&!state.completedActionIds.includes(a.id)&&a.status!=="archived").map(a=>a.id));const next={...state,goals:state.goals.map(g=>g.id===currentGoal.id?{...g,description:plan.description,milestones:plan.milestones,source:source==="ai-replan"?"ai":"local",planVersion:revision.version,updatedAt:new Date().toISOString()}:g),actions:[...state.actions.map(a=>archivedIds.has(a.id)?{...a,status:"archived"}:a),...nextActions],planRevisions:[...(state.planRevisions||[]),{...revision,goalId:currentGoal.id,source}]};persist(next)}
function solveBlocker(e){e.preventDefault();if(!blocker.trim())return;const result=analyzeBlocker(blocker);setBlockerResult(result);persist({...state,blockers:[...state.blockers,{id:crypto.randomUUID(),text:blocker,type:result.type,suggestion:result.suggestion,createdAt:new Date().toISOString()}]})}
const today=useMemo(()=>buildToday(state),[state]);const todayActions=today.actions;
return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">A</span><span>Aspirra</span></div><button className="icon-button" aria-label="New goal" onClick={()=>setShowGoal(true)}><Plus size={21}/></button></header>
<main className="content">{view==="home"&&<><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> PERSONAL PROGRESS SYSTEM</span><h1>Turn what you want into <span>what you do.</span></h1><p>Aspirra helps you turn goals into practical plans, daily actions, and measurable progress.</p></div><button className="primary-button" onClick={()=>setShowGoal(true)}>Start a goal <ArrowRight size={18}/></button></section>
<section className="progress-card"><div className="card-heading"><div><span className="label">YOUR PROGRESS</span><h2>{progress}% moving forward</h2></div><div className="progress-ring"><span>{progress}%</span></div></div><div className="progress-track"><span style={{width:progress+"%"}}/></div><p>{total?completed+" of "+total+" planned actions completed.":"Create your first goal to start building your progress history."}</p></section>
<section className="section"><div className="section-title"><span className="label">TODAY</span><h2>What should I do today?</h2></div>{todayActions.length?todayActions.map(action=><div className="action-wrap" key={action.id}><button className="action-card" onClick={()=>toggleAction(action.id)}><span className="check"><CheckCircle2 size={21}/></span><span><strong>{action.title}</strong><small>{action.detail}</small></span></button><button className="defer-button" onClick={()=>deferTodayAction(action.id)}>Defer</button></div>):<div className="empty-card"><Target size={26}/><strong>{currentGoal?"You’re caught up.":"Start with one meaningful goal."}</strong><p>{currentGoal?"Revisit your plan when your priorities change.":"Tell Aspirra what you want to achieve and we'll turn it into a practical starting plan."}</p></div>}</section>
<section className="feature-grid"><button onClick={()=>setView("guide")}><span className="feature-icon"><Bot size={20}/></span><strong>AI Guide</strong><small>Reason about your next move.</small></button><button onClick={()=>setView("progress")}><span className="feature-icon"><TrendingUp size={20}/></span><strong>Progress</strong><small>See what's moving and what's stuck.</small></button><button onClick={()=>setView("goals")}><span className="feature-icon"><Compass size={20}/></span><strong>Goals</strong><small>Keep your bigger direction visible.</small></button></section></>}
{view==="goals"&&<Page title="Goals" subtitle="The outcomes you are working toward."><div className="empty-card">{state.goals.length?state.goals.map(g=><div className="goal-item" key={g.id}><span className="label">{g.domain||"personal"}</span><strong className="goal-row">{g.title}</strong><small>{g.description}</small><div className="milestones">{(g.milestones||[]).map((m,i)=><span key={i}>{i+1}. {m}</span>)}</div></div>):<><Target size={28}/><strong>No goals yet</strong><p>Your first goal becomes the anchor for your plan and daily actions.</p></>}<button className="primary-button" onClick={()=>setShowGoal(true)}>Create goal</button></div></Page>}
{view==="progress"&&<Page title="Progress" subtitle="A simple view of movement, evidence, and the next adjustment."><div className="progress-card"><div className="big-number">{progress}%</div><p>{completed} completed actions out of {total} planned actions.</p></div>{currentGoal&&<><form className="guide-form" onSubmit={askGuide}><input value={guideInput} onChange={e=>setGuideInput(e.target.value)} placeholder="Ask Aspirra: What should I do today?" /><button className="primary-button" disabled={guideBusy}>{guideBusy?"Thinking…":"Ask Aspirra"}</button></form>{guideReply&&<div className="guide-reply"><Bot size={18}/><span>{guideReply}</span></div>}<div className="guide-card"><TrendingUp size={28}/><h2>Progress intelligence</h2><p>{buildReview(state,currentGoal.id).nextStep}</p><button className="secondary-button" onClick={revisePlan}>Mark for plan adjustment</button></div><div className="guide-card"><span className="label">EVIDENCE OF PROGRESS</span><h2>What actually happened?</h2><p>Record a result, completed application, study session, milestone, or other observable evidence.</p><form onSubmit={recordEvidence}><textarea name="evidence" placeholder="e.g. Completed two applications and received one interview invitation."/><button className="primary-button" type="submit">Save evidence <CheckCircle2 size={18}/></button></form>{(state.evidence||[]).filter(e=>e.goalId===currentGoal.id).slice(-3).reverse().map(e=><div className="evidence-row" key={e.id}>{e.text}</div>)}</div></>}</Page>}
{view==="guide"&&<Page title="AI Guide" subtitle="Aspirra's intelligence layer turns context into structured next steps."><div className="guide-card"><Brain size={30}/><h2>{currentGoal?"Working on: "+currentGoal.title:"Start with a goal"}</h2>{currentGoal?<><span className="label">DOMAIN · {currentGoal.domain||"personal"}</span><p>{currentGoal.description}</p>{(currentGoal.source==="ai"||currentGoal.source==="ai-replan")&&<span className="ai-badge"><Sparkles size={13}/> AI-PLANNED</span>}<div className="milestones">{(currentGoal.milestones||[]).map((m,i)=><span key={i}><CheckCircle2 size={16}/>{m}</span>)}</div></>:<p>Give Aspirra an outcome and it will create a structured starting plan.</p>}<button className="primary-button" onClick={()=>setShowGoal(true)}>Give it a goal</button></div>
<div className="guide-card blocker-box"><span className="eyebrow"><AlertCircle size={14}/> I'M STUCK</span><h2>What's getting in the way?</h2><p>Describe the blocker in plain language. Aspirra will turn it into a practical next move.</p><form onSubmit={solveBlocker}><textarea value={blocker} onChange={e=>setBlocker(e.target.value)} placeholder="e.g. I don't have enough time to work on this."/><button className="primary-button" type="submit">Help me move forward <ArrowRight size={18}/></button></form>{blockerResult&&<div className="blocker-result"><span className="label">SUGGESTED NEXT MOVE · {blockerResult.type.toUpperCase()}</span><strong>{blockerResult.suggestion}</strong></div>}</div></Page>}</main>
<nav className="bottom-nav">{[["home","Home"],["goals","Goals"],["progress","Progress"],["guide","AI Guide"]].map(([id,label])=><button className={view===id?"active":""} key={id} onClick={()=>setView(id)}>{id==="home"?<Compass/>:id==="goals"?<Target/>:id==="progress"?<TrendingUp/>:<Bot/>}<span>{label}</span></button>)}</nav>
{showGoal&&<div className="modal-backdrop" onClick={()=>setShowGoal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowGoal(false)}><X/></button><span className="eyebrow"><Target size={14}/> NEW GOAL</span><h2>What are you trying to achieve?</h2><p>Start with the outcome. Aspirra will turn it into practical first actions.</p><form onSubmit={createGoal}><textarea autoFocus value={goal} onChange={e=>setGoal(e.target.value)} placeholder="e.g. I want to find a better-paying job within six months."/><button className="primary-button" type="submit">Build my first plan <ArrowRight size={18}/></button></form></div></div>}</div>}
function Page({title,subtitle,children}){return <section className="page"><span className="label">ASPIRRA</span><h1>{title}</h1><p className="page-subtitle">{subtitle}</p>{children}</section>}export default App;